# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'I:/dev/AIYOU/AIYOU/app/resource/Pages/about.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_aboutWindow(object):
    def setupUi(self, aboutWindow):
        aboutWindow.setObjectName("aboutWindow")
        aboutWindow.resize(800, 600)
        aboutWindow.setMinimumSize(QtCore.QSize(800, 600))
        self.verticalLayout = QtWidgets.QVBoxLayout(aboutWindow)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mainBody = QtWidgets.QFrame(aboutWindow)
        self.mainBody.setStyleSheet("QFrame#mainBody{\n"
"    border:none;\n"
"    background-color:#f3f3f2;\n"
"}\n"
"QFrame#leftBox{\n"
"    border:none;\n"
"}\n"
"QFrame#rightBox{\n"
"    border:none;\n"
"}\n"
"QLabel#github{\n"
"    background-image: url(:/about/images/icons/icons8-github-20.png);\n"
"}\n"
"QLabel#discord{\n"
"    background-image: url(:/about/images/icons/icons8-discord-20.png);\n"
"}\n"
"QLabel#telegram{\n"
"    background-image: url(:/about/images/icons/icons8-telegram-20.png);\n"
"}\n"
"QLabel#wechat{\n"
"    background-image: url(:/about/images/icons/icons8-wechat-20.png);\n"
"}")
        self.mainBody.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainBody.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainBody.setObjectName("mainBody")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.mainBody)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.contentBody = QtWidgets.QFrame(self.mainBody)
        self.contentBody.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contentBody.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contentBody.setObjectName("contentBody")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.contentBody)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.leftBox = QtWidgets.QFrame(self.contentBody)
        self.leftBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.leftBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftBox.setObjectName("leftBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.leftBox)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(26, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.aboutText = QtWidgets.QFrame(self.leftBox)
        self.aboutText.setStyleSheet("QLabel#mainTitle{\n"
"    font: 1800 36pt \"Microsoft YaHei UI\";\n"
"}\n"
"QLabel#secondTitle{\n"
"    color: #6b798e;\n"
"    font: 10pt \"Microsoft YaHei UI\";\n"
"}\n"
"QLabel#content{\n"
"    font: 10pt \"Microsoft YaHei UI\";\n"
"}")
        self.aboutText.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.aboutText.setFrameShadow(QtWidgets.QFrame.Raised)
        self.aboutText.setObjectName("aboutText")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.aboutText)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.mainTitle = QtWidgets.QLabel(self.aboutText)
        self.mainTitle.setObjectName("mainTitle")
        self.verticalLayout_3.addWidget(self.mainTitle)
        self.secondTitle = QtWidgets.QLabel(self.aboutText)
        self.secondTitle.setObjectName("secondTitle")
        self.verticalLayout_3.addWidget(self.secondTitle)
        self.content = QtWidgets.QLabel(self.aboutText)
        self.content.setObjectName("content")
        self.verticalLayout_3.addWidget(self.content)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.verticalLayout_3.setStretch(1, 1)
        self.verticalLayout_3.setStretch(2, 1)
        self.verticalLayout_3.setStretch(3, 8)
        self.horizontalLayout_3.addWidget(self.aboutText)
        self.horizontalLayout_3.setStretch(1, 9)
        self.horizontalLayout_2.addWidget(self.leftBox)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.rightBox = QtWidgets.QFrame(self.contentBody)
        self.rightBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.rightBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.rightBox.setObjectName("rightBox")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.rightBox)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.rightBody = QtWidgets.QFrame(self.rightBox)
        self.rightBody.setStyleSheet("QFrame#contactBox{\n"
"    border:none;\n"
"}\n"
"\n"
"QLabel#aboutImg{\n"
"    background-image: url(:/about/images/ikun.jpg);\n"
"    border-radius:15px;\n"
"}\n"
"")
        self.rightBody.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.rightBody.setFrameShadow(QtWidgets.QFrame.Raised)
        self.rightBody.setObjectName("rightBody")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.rightBody)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem4 = QtWidgets.QSpacerItem(20, 143, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.aboutImg = QtWidgets.QLabel(self.rightBody)
        self.aboutImg.setMinimumSize(QtCore.QSize(264, 264))
        self.aboutImg.setText("")
        self.aboutImg.setObjectName("aboutImg")
        self.verticalLayout_2.addWidget(self.aboutImg)
        spacerItem5 = QtWidgets.QSpacerItem(20, 91, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.horizontalLayout_4.addWidget(self.rightBody)
        spacerItem6 = QtWidgets.QSpacerItem(26, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.horizontalLayout_4.setStretch(0, 9)
        self.horizontalLayout_2.addWidget(self.rightBox)
        self.horizontalLayout_2.setStretch(0, 6)
        self.horizontalLayout_2.setStretch(2, 4)
        self.verticalLayout_4.addWidget(self.contentBody)
        self.contactBox = QtWidgets.QFrame(self.mainBody)
        self.contactBox.setMaximumSize(QtCore.QSize(16777215, 30))
        self.contactBox.setStyleSheet("QFrame#contactBox{\n"
"    border:none;\n"
"}\n"
"QLabel#version{\n"
"    color:#9aa7b1;\n"
"    font: 9pt \"微软雅黑\";\n"
"}")
        self.contactBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contactBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contactBox.setObjectName("contactBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.contactBox)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem7)
        self.github = TransparentToolButton(self.contactBox)
        self.github.setObjectName("github")
        self.horizontalLayout.addWidget(self.github)
        self.discord = TransparentToolButton(self.contactBox)
        self.discord.setObjectName("discord")
        self.horizontalLayout.addWidget(self.discord)
        self.version = QtWidgets.QLabel(self.contactBox)
        self.version.setObjectName("version")
        self.horizontalLayout.addWidget(self.version)
        self.horizontalLayout.setStretch(0, 8)
        self.verticalLayout_4.addWidget(self.contactBox)
        self.verticalLayout.addWidget(self.mainBody)

        self.retranslateUi(aboutWindow)
        QtCore.QMetaObject.connectSlotsByName(aboutWindow)

    def retranslateUi(self, aboutWindow):
        _translate = QtCore.QCoreApplication.translate
        aboutWindow.setWindowTitle(_translate("aboutWindow", "about"))
        self.mainTitle.setText(_translate("aboutWindow", "AIYOU"))
        self.secondTitle.setText(_translate("aboutWindow", "哎呦，你干嘛~~"))
        self.content.setText(_translate("aboutWindow", "没想好这里写什么"))
        self.version.setText(_translate("aboutWindow", "Version：0.1-a"))
from qfluentwidgets import TransparentToolButton
from app.resource import KUN
