# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'I:/dev/AIYOU/AIYOU/app/resource/Pages/clientSwitch.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_clientSwitchWindow(object):
    def setupUi(self, clientSwitchWindow):
        clientSwitchWindow.setObjectName("clientSwitchWindow")
        clientSwitchWindow.resize(800, 600)
        clientSwitchWindow.setMinimumSize(QtCore.QSize(800, 600))
        clientSwitchWindow.setStyleSheet("QFrame#mainBody{\n"
"    border: 1px soild transparent;\n"
"    border-radius:10px;\n"
"    background-color:#f3f3f2;\n"
"}")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(clientSwitchWindow)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.mainBody = QtWidgets.QFrame(clientSwitchWindow)
        self.mainBody.setStyleSheet("QFrame#mainBody{\n"
"    border:none;\n"
"}")
        self.mainBody.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainBody.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainBody.setObjectName("mainBody")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.mainBody)
        self.verticalLayout.setSpacing(12)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabBox = QtWidgets.QFrame(self.mainBody)
        self.tabBox.setStyleSheet("QLabel#clientText{\n"
"    margin-left:10px;\n"
"    font: 500 14pt \"微软雅黑\";\n"
"}")
        self.tabBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tabBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tabBox.setObjectName("tabBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tabBox)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gameStartButton = QtWidgets.QPushButton(self.tabBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gameStartButton.sizePolicy().hasHeightForWidth())
        self.gameStartButton.setSizePolicy(sizePolicy)
        self.gameStartButton.setMinimumSize(QtCore.QSize(120, 40))
        self.gameStartButton.setMaximumSize(QtCore.QSize(16777215, 40))
        self.gameStartButton.setStyleSheet("border-radius:10px;\n"
"background-color: #2b2828;\n"
"color: #ffffff;\n"
"font: 400 12pt \"微软雅黑\";")
        self.gameStartButton.setCheckable(False)
        self.gameStartButton.setObjectName("gameStartButton")
        self.horizontalLayout.addWidget(self.gameStartButton)
        self.verticalLayout.addWidget(self.tabBox)
        self.switchMainBox = QtWidgets.QFrame(self.mainBody)
        self.switchMainBox.setStyleSheet("QFrame#clientVersionBox{\n"
"    border-radius:10px;\n"
"    background-color:rgba(107, 121, 142, 15);\n"
"}\n"
"QFrame#loadModBox{\n"
"    border-radius:10px;\n"
"    background-color:rgba(107, 121, 142, 15);\n"
"}\n"
"QFrame#fullScreenBox{\n"
"    border-radius:10px;\n"
"    background-color:rgba(107, 121, 142, 15);\n"
"}\n"
"QFrame#windowSizeBox{\n"
"    border-radius:10px;\n"
"    background-color:rgba(107, 121, 142, 15);\n"
"}")
        self.switchMainBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.switchMainBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.switchMainBox.setObjectName("switchMainBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.switchMainBox)
        self.verticalLayout_3.setContentsMargins(0, 6, 0, 6)
        self.verticalLayout_3.setSpacing(20)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.clientVersionBox = QtWidgets.QFrame(self.switchMainBox)
        self.clientVersionBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.clientVersionBox.setStyleSheet("")
        self.clientVersionBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.clientVersionBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.clientVersionBox.setObjectName("clientVersionBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.clientVersionBox)
        self.horizontalLayout_2.setContentsMargins(16, -1, 16, -1)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.clientVersionLabel = QtWidgets.QLabel(self.clientVersionBox)
        self.clientVersionLabel.setStyleSheet("font: 400 12pt \"微软雅黑\";")
        self.clientVersionLabel.setObjectName("clientVersionLabel")
        self.horizontalLayout_2.addWidget(self.clientVersionLabel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.clientSelect = ComboBox(self.clientVersionBox)
        self.clientSelect.setMaximumSize(QtCore.QSize(219, 16777215))
        self.clientSelect.setObjectName("clientSelect")
        self.horizontalLayout_2.addWidget(self.clientSelect)
        self.horizontalLayout_2.setStretch(1, 4)
        self.horizontalLayout_2.setStretch(2, 3)
        self.verticalLayout_3.addWidget(self.clientVersionBox)
        self.gameSettingBox = QtWidgets.QFrame(self.switchMainBox)
        self.gameSettingBox.setStyleSheet("QLabel#settingText{\n"
"    margin-left:10px;\n"
"}")
        self.gameSettingBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.gameSettingBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.gameSettingBox.setObjectName("gameSettingBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.gameSettingBox)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.settingText = QtWidgets.QLabel(self.gameSettingBox)
        self.settingText.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.settingText.setStyleSheet("font: 500 14pt \"微软雅黑\";")
        self.settingText.setObjectName("settingText")
        self.verticalLayout_4.addWidget(self.settingText)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.loadModBox = QtWidgets.QFrame(self.gameSettingBox)
        self.loadModBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.loadModBox.setStyleSheet("")
        self.loadModBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.loadModBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.loadModBox.setObjectName("loadModBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.loadModBox)
        self.horizontalLayout_3.setContentsMargins(16, -1, 16, -1)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.loadModLabel = QtWidgets.QLabel(self.loadModBox)
        self.loadModLabel.setStyleSheet("font: 400 12pt \"微软雅黑\";")
        self.loadModLabel.setObjectName("loadModLabel")
        self.horizontalLayout_3.addWidget(self.loadModLabel)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.loadSwitchButton = SwitchButton(self.loadModBox)
        self.loadSwitchButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.loadSwitchButton.setChecked(False)
        self.loadSwitchButton.setObjectName("loadSwitchButton")
        self.horizontalLayout_3.addWidget(self.loadSwitchButton)
        self.horizontalLayout_3.setStretch(1, 7)
        self.horizontalLayout_3.setStretch(2, 1)
        self.verticalLayout_4.addWidget(self.loadModBox)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem4)
        self.fullScreenBox = QtWidgets.QFrame(self.gameSettingBox)
        self.fullScreenBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.fullScreenBox.setStyleSheet("")
        self.fullScreenBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fullScreenBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fullScreenBox.setObjectName("fullScreenBox")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.fullScreenBox)
        self.horizontalLayout_4.setContentsMargins(16, -1, 16, -1)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.fullScreenLabel = QtWidgets.QLabel(self.fullScreenBox)
        self.fullScreenLabel.setStyleSheet("font: 400 12pt \"微软雅黑\";")
        self.fullScreenLabel.setObjectName("fullScreenLabel")
        self.horizontalLayout_4.addWidget(self.fullScreenLabel)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.fullScreenSelect = ComboBox(self.fullScreenBox)
        self.fullScreenSelect.setMaximumSize(QtCore.QSize(219, 16777215))
        self.fullScreenSelect.setObjectName("fullScreenSelect")
        self.horizontalLayout_4.addWidget(self.fullScreenSelect)
        self.horizontalLayout_4.setStretch(1, 4)
        self.horizontalLayout_4.setStretch(2, 3)
        self.verticalLayout_4.addWidget(self.fullScreenBox)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem6)
        self.windowSizeBox = QtWidgets.QFrame(self.gameSettingBox)
        self.windowSizeBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.windowSizeBox.setStyleSheet("")
        self.windowSizeBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.windowSizeBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.windowSizeBox.setObjectName("windowSizeBox")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.windowSizeBox)
        self.horizontalLayout_5.setContentsMargins(16, -1, 16, -1)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.windowSizeLabel = QtWidgets.QLabel(self.windowSizeBox)
        self.windowSizeLabel.setStyleSheet("font: 400 12pt \"微软雅黑\";")
        self.windowSizeLabel.setObjectName("windowSizeLabel")
        self.horizontalLayout_5.addWidget(self.windowSizeLabel)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem7)
        self.windowSizeSelect = ComboBox(self.windowSizeBox)
        self.windowSizeSelect.setMaximumSize(QtCore.QSize(219, 16777215))
        self.windowSizeSelect.setObjectName("windowSizeSelect")
        self.horizontalLayout_5.addWidget(self.windowSizeSelect)
        self.horizontalLayout_5.setStretch(1, 4)
        self.horizontalLayout_5.setStretch(2, 3)
        self.verticalLayout_4.addWidget(self.windowSizeBox)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem8)
        self.verticalLayout_4.setStretch(0, 1)
        self.verticalLayout_4.setStretch(2, 3)
        self.verticalLayout_4.setStretch(4, 3)
        self.verticalLayout_4.setStretch(6, 3)
        self.verticalLayout_3.addWidget(self.gameSettingBox)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 6)
        self.verticalLayout.addWidget(self.switchMainBox)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 8)
        self.verticalLayout_2.addWidget(self.mainBody)

        self.retranslateUi(clientSwitchWindow)
        QtCore.QMetaObject.connectSlotsByName(clientSwitchWindow)

    def retranslateUi(self, clientSwitchWindow):
        _translate = QtCore.QCoreApplication.translate
        clientSwitchWindow.setWindowTitle(_translate("clientSwitchWindow", "clientSwitch"))
        self.gameStartButton.setText(_translate("clientSwitchWindow", "IKUN，启动！"))
        self.clientVersionLabel.setText(_translate("clientSwitchWindow", "服务器版本（国服/国际服）"))
        self.settingText.setText(_translate("clientSwitchWindow", "启动参数"))
        self.loadModLabel.setText(_translate("clientSwitchWindow", "加载模组（-fileopenlog）"))
        self.loadSwitchButton.setOnText(_translate("clientSwitchWindow", "开"))
        self.loadSwitchButton.setOffText(_translate("clientSwitchWindow", "关"))
        self.fullScreenLabel.setText(_translate("clientSwitchWindow", "全屏/窗口化"))
        self.windowSizeLabel.setText(_translate("clientSwitchWindow", "窗口尺寸"))
from qfluentwidgets import ComboBox, SwitchButton
