# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'I:/dev/AIYOU/AIYOU/app/resource/Pages/modManager.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_modWindow(object):
    def setupUi(self, modWindow):
        modWindow.setObjectName("modWindow")
        modWindow.resize(800, 600)
        modWindow.setStyleSheet("border: 1px soild transparent;\n"
"border-radius:10px;\n"
"background-color:#f3f3f2;\n"
"")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(modWindow)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.selectBox = QtWidgets.QFrame(modWindow)
        self.selectBox.setStyleSheet("PushButton{\n"
"    font: 10pt \"微软雅黑\";\n"
"}")
        self.selectBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.selectBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.selectBox.setObjectName("selectBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.selectBox)
        self.horizontalLayout_2.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.selectDownload = PushButton(self.selectBox)
        self.selectDownload.setObjectName("selectDownload")
        self.horizontalLayout_2.addWidget(self.selectDownload)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.openModFolder = PushButton(self.selectBox)
        self.openModFolder.setObjectName("openModFolder")
        self.horizontalLayout_2.addWidget(self.openModFolder)
        self.horizontalLayout_2.setStretch(0, 6)
        self.verticalLayout_2.addWidget(self.selectBox)
        self.folderTextBox = QtWidgets.QFrame(modWindow)
        self.folderTextBox.setStyleSheet("QLabel{\n"
"    font: 500 11pt \"微软雅黑\";\n"
"}")
        self.folderTextBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.folderTextBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.folderTextBox.setObjectName("folderTextBox")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.folderTextBox)
        self.horizontalLayout_4.setSpacing(16)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.downloadLabel = QtWidgets.QLabel(self.folderTextBox)
        self.downloadLabel.setObjectName("downloadLabel")
        self.horizontalLayout_4.addWidget(self.downloadLabel)
        self.ModLabel = QtWidgets.QLabel(self.folderTextBox)
        self.ModLabel.setObjectName("ModLabel")
        self.horizontalLayout_4.addWidget(self.ModLabel)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 1)
        self.verticalLayout_2.addWidget(self.folderTextBox)
        self.folderBox = QtWidgets.QFrame(modWindow)
        self.folderBox.setStyleSheet("")
        self.folderBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.folderBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.folderBox.setObjectName("folderBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.folderBox)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.downloadFolder = TreeWidget(self.folderBox)
        self.downloadFolder.setObjectName("downloadFolder")
        self.downloadFolder.headerItem().setText(0, "1")
        self.horizontalLayout.addWidget(self.downloadFolder)
        self.modFolder = TreeWidget(self.folderBox)
        self.modFolder.setObjectName("modFolder")
        self.modFolder.headerItem().setText(0, "1")
        self.horizontalLayout.addWidget(self.modFolder)
        self.verticalLayout_2.addWidget(self.folderBox)
        self.confirmBox = QtWidgets.QFrame(modWindow)
        self.confirmBox.setStyleSheet("PushButton{\n"
"    font: 10pt \"微软雅黑\";\n"
"}\n"
"PrimaryPushButton{\n"
"    font: 10pt \"微软雅黑\";\n"
"}")
        self.confirmBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.confirmBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.confirmBox.setObjectName("confirmBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.confirmBox)
        self.horizontalLayout_3.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.confirmButton = PrimaryPushButton(self.confirmBox)
        self.confirmButton.setObjectName("confirmButton")
        self.horizontalLayout_3.addWidget(self.confirmButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.refreshButton = PushButton(self.confirmBox)
        self.refreshButton.setObjectName("refreshButton")
        self.horizontalLayout_3.addWidget(self.refreshButton)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.deleteButton = PushButton(self.confirmBox)
        self.deleteButton.setObjectName("deleteButton")
        self.horizontalLayout_3.addWidget(self.deleteButton)
        self.horizontalLayout_3.setStretch(0, 6)
        self.horizontalLayout_3.setStretch(2, 4)
        self.verticalLayout_2.addWidget(self.confirmBox)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.setStretch(2, 7)
        self.verticalLayout_2.setStretch(3, 1)

        self.retranslateUi(modWindow)
        QtCore.QMetaObject.connectSlotsByName(modWindow)

    def retranslateUi(self, modWindow):
        _translate = QtCore.QCoreApplication.translate
        modWindow.setWindowTitle(_translate("modWindow", "modManager"))
        self.selectDownload.setText(_translate("modWindow", "选择下载文件夹"))
        self.openModFolder.setText(_translate("modWindow", "打开Mod文件夹"))
        self.downloadLabel.setText(_translate("modWindow", "下载文件夹"))
        self.ModLabel.setText(_translate("modWindow", "Mod文件夹"))
        self.confirmButton.setText(_translate("modWindow", "添   加"))
        self.refreshButton.setText(_translate("modWindow", "刷  新"))
        self.deleteButton.setText(_translate("modWindow", "删  除"))
from qfluentwidgets import PrimaryPushButton, PushButton, TreeWidget
