# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'I:/dev/AIYOU/AIYOU/app/resource/Pages/setting.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_settingWindow(object):
    def setupUi(self, settingWindow):
        settingWindow.setObjectName("settingWindow")
        settingWindow.resize(835, 600)
        settingWindow.setStyleSheet("QFrame#mainBody{\n"
"    border: 1px soild transparent;\n"
"    border-radius:10px;\n"
"    background-color:#f3f3f2;\n"
"}")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(settingWindow)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.mainBody = QtWidgets.QFrame(settingWindow)
        self.mainBody.setStyleSheet("QLabel#storageLabel{\n"
"    font: 500 12pt \"微软雅黑\";\n"
"    margin-left: 20px;\n"
"}\n"
"QLabel#aboutLabel{\n"
"    font: 500 12pt \"微软雅黑\";\n"
"    margin-left: 20px;\n"
"}\n"
"\n"
"QFrame#cacheFolderBox{\n"
"    border-radius:10px;\n"
"    background-color:rgba(107, 121, 142, 15);\n"
"}\n"
"QFrame#programFolderBox{\n"
"    border-radius:10px;\n"
"    background-color:rgba(107, 121, 142, 15);\n"
"}\n"
"QFrame#pushIssuesBox{\n"
"    border-radius:10px;\n"
"    background-color:rgba(107, 121, 142, 15);\n"
"}\n"
"QFrame#aboutBox{\n"
"    border-radius:10px;\n"
"    background-color:rgba(107, 121, 142, 15);\n"
"}")
        self.mainBody.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainBody.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainBody.setObjectName("mainBody")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.mainBody)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(16)
        self.verticalLayout.setObjectName("verticalLayout")
        self.storageLabel = QtWidgets.QLabel(self.mainBody)
        self.storageLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.storageLabel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.storageLabel.setObjectName("storageLabel")
        self.verticalLayout.addWidget(self.storageLabel)
        self.programFolderBox = QtWidgets.QFrame(self.mainBody)
        self.programFolderBox.setMinimumSize(QtCore.QSize(0, 0))
        self.programFolderBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.programFolderBox.setStyleSheet("PushButton#openFolderButton{\n"
"    font: 10pt \"微软雅黑\";\n"
"}")
        self.programFolderBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.programFolderBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.programFolderBox.setObjectName("programFolderBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.programFolderBox)
        self.horizontalLayout_2.setContentsMargins(16, -1, 16, -1)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.programFolderInfoBox = QtWidgets.QFrame(self.programFolderBox)
        self.programFolderInfoBox.setMinimumSize(QtCore.QSize(600, 0))
        self.programFolderInfoBox.setMaximumSize(QtCore.QSize(600, 80))
        self.programFolderInfoBox.setStyleSheet("QFrame#programFolderInfoBox{\n"
"    background-color: transparent;\n"
"    background-image: url(:/setting/images/icons/icons8-user-folder-30.png);\n"
"    background-repeat: no-repeat;\n"
"    background-position: left center;\n"
"}\n"
"QLabel{\n"
"    margin-left:30px;\n"
"}\n"
"QLabel#programFolderTitle{\n"
"    background-color: transparent;\n"
"    font: 500 11pt \"微软雅黑\";\n"
"}\n"
"QLabel#programFolderInfo{\n"
"    background-color: transparent;\n"
"    font: 8pt \"微软雅黑\";\n"
"    color: #9aa7b1;\n"
"}")
        self.programFolderInfoBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.programFolderInfoBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.programFolderInfoBox.setObjectName("programFolderInfoBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.programFolderInfoBox)
        self.verticalLayout_3.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_3.setSpacing(12)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.programFolderTitle = QtWidgets.QLabel(self.programFolderInfoBox)
        self.programFolderTitle.setStyleSheet("")
        self.programFolderTitle.setObjectName("programFolderTitle")
        self.verticalLayout_3.addWidget(self.programFolderTitle)
        self.programFolderInfo = QtWidgets.QLabel(self.programFolderInfoBox)
        self.programFolderInfo.setStyleSheet("")
        self.programFolderInfo.setText("")
        self.programFolderInfo.setObjectName("programFolderInfo")
        self.verticalLayout_3.addWidget(self.programFolderInfo)
        self.horizontalLayout_2.addWidget(self.programFolderInfoBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.openFolderButton = PushButton(self.programFolderBox)
        self.openFolderButton.setObjectName("openFolderButton")
        self.horizontalLayout_2.addWidget(self.openFolderButton)
        self.horizontalLayout_2.setStretch(1, 4)
        self.verticalLayout.addWidget(self.programFolderBox)
        self.cacheFolderBox = QtWidgets.QFrame(self.mainBody)
        self.cacheFolderBox.setMinimumSize(QtCore.QSize(0, 0))
        self.cacheFolderBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cacheFolderBox.setStyleSheet("")
        self.cacheFolderBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cacheFolderBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cacheFolderBox.setObjectName("cacheFolderBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.cacheFolderBox)
        self.horizontalLayout.setContentsMargins(16, -1, 16, -1)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cacheFolderInfoBox = QtWidgets.QFrame(self.cacheFolderBox)
        self.cacheFolderInfoBox.setMinimumSize(QtCore.QSize(600, 0))
        self.cacheFolderInfoBox.setMaximumSize(QtCore.QSize(600, 60))
        self.cacheFolderInfoBox.setStyleSheet("QFrame#cacheFolderInfoBox{\n"
"    background-color: transparent;\n"
"    background-image: url(:/setting/images/icons/icons8-folder-30.png);\n"
"    background-repeat: no-repeat;\n"
"    background-position: left center;\n"
"}\n"
"QLabel{\n"
"    margin-left:30px;\n"
"}\n"
"QLabel#cacheFolderTitle{\n"
"    background-color: transparent;\n"
"    font: 500 11pt \"微软雅黑\";\n"
"}\n"
"QLabel#cacheFolderInfo{\n"
"    background-color: transparent;\n"
"    font: 8pt \"微软雅黑\";\n"
"    color: #9aa7b1;\n"
"}")
        self.cacheFolderInfoBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cacheFolderInfoBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cacheFolderInfoBox.setObjectName("cacheFolderInfoBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.cacheFolderInfoBox)
        self.verticalLayout_4.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_4.setSpacing(12)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.cacheFolderTitle = QtWidgets.QLabel(self.cacheFolderInfoBox)
        self.cacheFolderTitle.setStyleSheet("")
        self.cacheFolderTitle.setObjectName("cacheFolderTitle")
        self.verticalLayout_4.addWidget(self.cacheFolderTitle)
        self.cacheFolderInfo = QtWidgets.QLabel(self.cacheFolderInfoBox)
        self.cacheFolderInfo.setStyleSheet("")
        self.cacheFolderInfo.setText("")
        self.cacheFolderInfo.setObjectName("cacheFolderInfo")
        self.verticalLayout_4.addWidget(self.cacheFolderInfo)
        self.horizontalLayout.addWidget(self.cacheFolderInfoBox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.cacheFolderButtonBox = QtWidgets.QFrame(self.cacheFolderBox)
        self.cacheFolderButtonBox.setStyleSheet("QFrame#cacheFolderButtonBox{\n"
"    background-color: transparent;\n"
"}\n"
"PushButton#cleancacheFolderButton{\n"
"    font: 10pt \"微软雅黑\";\n"
"}\n"
"PushButton#opencacheFolderButton{\n"
"    font: 10pt \"微软雅黑\";\n"
"}")
        self.cacheFolderButtonBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cacheFolderButtonBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cacheFolderButtonBox.setObjectName("cacheFolderButtonBox")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.cacheFolderButtonBox)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(12)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.cleancacheFolderButton = PushButton(self.cacheFolderButtonBox)
        self.cleancacheFolderButton.setObjectName("cleancacheFolderButton")
        self.horizontalLayout_5.addWidget(self.cleancacheFolderButton)
        self.opencacheFolderButton = PushButton(self.cacheFolderButtonBox)
        self.opencacheFolderButton.setObjectName("opencacheFolderButton")
        self.horizontalLayout_5.addWidget(self.opencacheFolderButton)
        self.horizontalLayout.addWidget(self.cacheFolderButtonBox)
        self.verticalLayout.addWidget(self.cacheFolderBox)
        self.aboutLabel = QtWidgets.QLabel(self.mainBody)
        self.aboutLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.aboutLabel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.aboutLabel.setObjectName("aboutLabel")
        self.verticalLayout.addWidget(self.aboutLabel)
        self.pushIssuesBox = QtWidgets.QFrame(self.mainBody)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushIssuesBox.sizePolicy().hasHeightForWidth())
        self.pushIssuesBox.setSizePolicy(sizePolicy)
        self.pushIssuesBox.setMinimumSize(QtCore.QSize(0, 0))
        self.pushIssuesBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushIssuesBox.setStyleSheet("")
        self.pushIssuesBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.pushIssuesBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pushIssuesBox.setObjectName("pushIssuesBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.pushIssuesBox)
        self.horizontalLayout_3.setContentsMargins(16, -1, 16, -1)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushIssuesInfoBox = QtWidgets.QFrame(self.pushIssuesBox)
        self.pushIssuesInfoBox.setMinimumSize(QtCore.QSize(400, 0))
        self.pushIssuesInfoBox.setMaximumSize(QtCore.QSize(400, 80))
        self.pushIssuesInfoBox.setStyleSheet("QFrame#pushIssuesInfoBox{\n"
"    background-color: transparent;\n"
"    background-image: url(:/setting/images/icons/icons8-help-30.png);\n"
"    background-repeat: no-repeat;\n"
"    background-position: left center;\n"
"}\n"
"QLabel{\n"
"    margin-left:30px;\n"
"}\n"
"QLabel#pushIssuesTitle{\n"
"    background-color: transparent;\n"
"    font: 500 11pt \"微软雅黑\";\n"
"}\n"
"QLabel#pushIssuesInfo{\n"
"    background-color: transparent;\n"
"    font: 8pt \"微软雅黑\";\n"
"    color: #9aa7b1;\n"
"}")
        self.pushIssuesInfoBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.pushIssuesInfoBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pushIssuesInfoBox.setObjectName("pushIssuesInfoBox")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.pushIssuesInfoBox)
        self.verticalLayout_6.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pushIssuesTitle = QtWidgets.QLabel(self.pushIssuesInfoBox)
        self.pushIssuesTitle.setStyleSheet("")
        self.pushIssuesTitle.setObjectName("pushIssuesTitle")
        self.verticalLayout_6.addWidget(self.pushIssuesTitle)
        self.pushIssuesInfo = QtWidgets.QLabel(self.pushIssuesInfoBox)
        self.pushIssuesInfo.setObjectName("pushIssuesInfo")
        self.verticalLayout_6.addWidget(self.pushIssuesInfo)
        self.horizontalLayout_3.addWidget(self.pushIssuesInfoBox)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.pushIssuesButton = PushButton(self.pushIssuesBox)
        self.pushIssuesButton.setMinimumSize(QtCore.QSize(91, 0))
        self.pushIssuesButton.setObjectName("pushIssuesButton")
        self.horizontalLayout_3.addWidget(self.pushIssuesButton)
        self.verticalLayout.addWidget(self.pushIssuesBox)
        self.aboutBox = QtWidgets.QFrame(self.mainBody)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.aboutBox.sizePolicy().hasHeightForWidth())
        self.aboutBox.setSizePolicy(sizePolicy)
        self.aboutBox.setMinimumSize(QtCore.QSize(0, 0))
        self.aboutBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.aboutBox.setStyleSheet("")
        self.aboutBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.aboutBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.aboutBox.setObjectName("aboutBox")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.aboutBox)
        self.horizontalLayout_4.setContentsMargins(16, -1, 16, -1)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.aboutInfoBox = QtWidgets.QFrame(self.aboutBox)
        self.aboutInfoBox.setMinimumSize(QtCore.QSize(400, 0))
        self.aboutInfoBox.setMaximumSize(QtCore.QSize(400, 80))
        self.aboutInfoBox.setStyleSheet("QFrame#aboutInfoBox{\n"
"    background-color: transparent;\n"
"    background-image: url(:/setting/images/icons/icons8-update-30.png);\n"
"    background-repeat: no-repeat;\n"
"    background-position: left center;\n"
"}\n"
"QLabel{\n"
"    margin-left:30px;\n"
"}\n"
"QLabel#aboutTitle{\n"
"    background-color: transparent;\n"
"    font: 500 11pt \"微软雅黑\";\n"
"}\n"
"QLabel#aboutInfo{\n"
"    background-color: transparent;\n"
"    font: 8pt \"微软雅黑\";\n"
"    color: #9aa7b1;\n"
"}")
        self.aboutInfoBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.aboutInfoBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.aboutInfoBox.setObjectName("aboutInfoBox")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.aboutInfoBox)
        self.verticalLayout_7.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.aboutTitle = QtWidgets.QLabel(self.aboutInfoBox)
        self.aboutTitle.setStyleSheet("")
        self.aboutTitle.setObjectName("aboutTitle")
        self.verticalLayout_7.addWidget(self.aboutTitle)
        self.aboutInfo = QtWidgets.QLabel(self.aboutInfoBox)
        self.aboutInfo.setText("")
        self.aboutInfo.setObjectName("aboutInfo")
        self.verticalLayout_7.addWidget(self.aboutInfo)
        self.horizontalLayout_4.addWidget(self.aboutInfoBox)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.checkUpdateButton = PushButton(self.aboutBox)
        self.checkUpdateButton.setMinimumSize(QtCore.QSize(91, 0))
        self.checkUpdateButton.setObjectName("checkUpdateButton")
        self.horizontalLayout_4.addWidget(self.checkUpdateButton)
        self.verticalLayout.addWidget(self.aboutBox)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.verticalLayout_2.addWidget(self.mainBody)

        self.retranslateUi(settingWindow)
        QtCore.QMetaObject.connectSlotsByName(settingWindow)

    def retranslateUi(self, settingWindow):
        _translate = QtCore.QCoreApplication.translate
        settingWindow.setWindowTitle(_translate("settingWindow", "setting"))
        self.storageLabel.setText(_translate("settingWindow", "存储空间"))
        self.programFolderTitle.setText(_translate("settingWindow", "程序数据文件夹"))
        self.openFolderButton.setText(_translate("settingWindow", "打开文件夹"))
        self.cacheFolderTitle.setText(_translate("settingWindow", "服务器转换缓存文件夹"))
        self.cleancacheFolderButton.setText(_translate("settingWindow", "清理缓存"))
        self.opencacheFolderButton.setText(_translate("settingWindow", "打开文件夹"))
        self.aboutLabel.setText(_translate("settingWindow", "关于"))
        self.pushIssuesTitle.setText(_translate("settingWindow", "提供反馈"))
        self.pushIssuesInfo.setText(_translate("settingWindow", "提供任何反馈以帮助我改进程序"))
        self.pushIssuesButton.setText(_translate("settingWindow", "提供反馈"))
        self.aboutTitle.setText(_translate("settingWindow", "版本信息"))
        self.checkUpdateButton.setText(_translate("settingWindow", "检查更新"))
from qfluentwidgets import PushButton
from app.resource import KUN