# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'I:/dev/AIYOU/AIYOU/app/resource/Pages/TPFileManager.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TPfileWindow(object):
    def setupUi(self, TPfileWindow):
        TPfileWindow.setObjectName("TPfileWindow")
        TPfileWindow.resize(800, 600)
        TPfileWindow.setStyleSheet("background-color: #f3f3f2;")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(TPfileWindow)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.mainBody = QtWidgets.QFrame(TPfileWindow)
        self.mainBody.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainBody.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainBody.setObjectName("mainBody")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.mainBody)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.usageBox = QtWidgets.QFrame(self.mainBody)
        self.usageBox.setStyleSheet("PushButton#usageButton{\n"
"    font: 10pt \"微软雅黑\";\n"
"}\n"
"PushButton#selectFolderButton{\n"
"    font: 10pt \"微软雅黑\";\n"
"}\n"
"PushButton#analysisButton{\n"
"    font: 10pt \"微软雅黑\";\n"
"}")
        self.usageBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.usageBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.usageBox.setObjectName("usageBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.usageBox)
        self.horizontalLayout_2.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.usageButton = PushButton(self.usageBox)
        self.usageButton.setObjectName("usageButton")
        self.horizontalLayout_2.addWidget(self.usageButton)
        spacerItem = QtWidgets.QSpacerItem(685, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.selectFolderButton = PushButton(self.usageBox)
        self.selectFolderButton.setObjectName("selectFolderButton")
        self.horizontalLayout_2.addWidget(self.selectFolderButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.analysisButton = PushButton(self.usageBox)
        self.analysisButton.setObjectName("analysisButton")
        self.horizontalLayout_2.addWidget(self.analysisButton)
        self.horizontalLayout_2.setStretch(1, 6)
        self.verticalLayout.addWidget(self.usageBox)
        self.folderBox = QtWidgets.QFrame(self.mainBody)
        self.folderBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.folderBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.folderBox.setObjectName("folderBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.folderBox)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.downloadFolder = TreeWidget(self.folderBox)
        self.downloadFolder.setObjectName("downloadFolder")
        self.downloadFolder.headerItem().setText(0, "1")
        self.horizontalLayout.addWidget(self.downloadFolder)
        self.customTPFolder = TreeWidget(self.folderBox)
        self.customTPFolder.setObjectName("customTPFolder")
        self.customTPFolder.headerItem().setText(0, "1")
        self.horizontalLayout.addWidget(self.customTPFolder)
        self.verticalLayout.addWidget(self.folderBox)
        self.bottomBox = QtWidgets.QFrame(self.mainBody)
        self.bottomBox.setStyleSheet("PushButton#deleteButton{\n"
"    font: 10pt \"微软雅黑\";\n"
"}\n"
"PushButton#confirmButton{\n"
"    font: 10pt \"微软雅黑\";\n"
"}")
        self.bottomBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bottomBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottomBox.setObjectName("bottomBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.bottomBox)
        self.horizontalLayout_3.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(612, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.deleteButton = PushButton(self.bottomBox)
        self.deleteButton.setObjectName("deleteButton")
        self.horizontalLayout_3.addWidget(self.deleteButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.confirmButton = PrimaryPushButton(self.bottomBox)
        self.confirmButton.setObjectName("confirmButton")
        self.horizontalLayout_3.addWidget(self.confirmButton)
        self.horizontalLayout_3.setStretch(0, 6)
        self.verticalLayout.addWidget(self.bottomBox)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 8)
        self.verticalLayout.setStretch(2, 1)
        self.verticalLayout_2.addWidget(self.mainBody)

        self.retranslateUi(TPfileWindow)
        QtCore.QMetaObject.connectSlotsByName(TPfileWindow)

    def retranslateUi(self, TPfileWindow):
        _translate = QtCore.QCoreApplication.translate
        TPfileWindow.setWindowTitle(_translate("TPfileWindow", "TPFileManager"))
        self.usageButton.setText(_translate("TPfileWindow", "使 用 方 法"))
        self.selectFolderButton.setText(_translate("TPfileWindow", "选择下载文件夹"))
        self.analysisButton.setText(_translate("TPfileWindow", "解析TP文件"))
        self.deleteButton.setText(_translate("TPfileWindow", "删  除"))
        self.confirmButton.setText(_translate("TPfileWindow", "生成自定义TP文件"))
from qfluentwidgets import PrimaryPushButton, PushButton, TreeWidget
